CREATE TABLE IF NOT EXISTS mainmenu(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wells(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    field TEXT NOT NULL,
    num INTEGER NOT NULL,
    text TEXT NOT NULL,
    depth INTEGER NOT NULL,
    time INTEGER NOT NULL
)
