# Generated by Django 3.0.14 on 2023-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(default='default.jpg', upload_to='projects/%Y/%m/%d/'),
        ),
    ]
